[package]
name = "graph-img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgraphs = { path = "../" }
image = "0.24.5"
rusttype = "0.9.3"
imageproc = "0.23.0"
json = "0.12.4"